name: PHP-FPM DEV

on:
  workflow_run:
    workflows: [ "PHP-FPM" ]
    types: [ completed ]
    # Optional: allow manual runs
    workflow_dispatch:

permissions:
  contents: read
  packages: write         # push to GHCR
  id-token: write         # cosign keyless

env:
  DOCKERHUB_NS: liquidrazor
  GHCR_NS: ghcr.io/liquidrazor"

  # Patch versions (immutable tag source)
  PHP_84: ${{ vars.PHP_84_VERSION }}
  PHP_83: ${{ vars.PHP_83_VERSION }}

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # -------- PHP 8.4 --------
          - php_line: 8.4
            php_version_env: PHP_84
            base_target: fpm
            tags: 8.4-fpm-dev,fpm-dev
          # -------- PHP 8.3 --------
          - php_line: 8.3
            php_version_env: PHP_83
            base_target: fpm
            tags: 8.3-fpm-dev

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      # Login to GHCR
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Login to Docker Hub
      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push ${{ matrix.php_line }} ${{ matrix.target }}
        id: build
        uses: docker/build-push-action@v6
        with:
          context: docker/php/fpm/development
          file: docker/php/fpm/development/Dockerfile
          target: ${{ matrix.target }}
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_VERSION=${{ env[matrix.php_version_env] }}
            BASE_IMAGE=${{ env.GHCR_NS }}/php:${{ env[matrix.php_version_env] }}-${{ matrix.base_target }}
          # Separate caches per PHP line and target
          cache-from: type=gha,scope=${{ matrix.php_line }}-${{ matrix.target }}
          cache-to: type=gha,mode=max,scope=${{ matrix.php_line }}-${{ matrix.target }}
          # ---- TAGS: rolling + immutable (patch-pinned) ----
          tags: |
            ${{ env.GHCR_NS }}/php:${{ matrix.tags }}
            docker.io/${{ env.DOCKERHUB_NS }}/php:${{ matrix.tags }}
            ${{ env.GHCR_NS }}/php:${{ env[matrix.php_version_env] }}-${{ matrix.target }}
            docker.io/${{ env.DOCKERHUB_NS }}/php:${{ env[matrix.php_version_env] }}-${{ matrix.target }}